SELECT * FROM temp.ACCOUNT;

CREATE TABLE ACCOUNT(
ID INT PRIMARY KEY,
NAME VARCHAR(255) UNIQUE,
BALANCE INT,
CONSTRAINT ACC_BALANCE_CHK CHECK (BALANCE > 1000)
);

SELECT * FROM ACCOUNT;

-- ADD NEW COLUMN
ALTER TABLE ACCOUNT ADD INTEREST FLOAT NOT NULL DEFAULT 0;

-- MODIFY DATA TYPE
ALTER TABLE ACCOUNT MODIFY INTEREST DOUBLE NOT NULL DEFAULT 0;

DESC ACCOUNT;

-- CHANGE COLUMN NAME - RENAME COLUMN NAME
ALTER TABLE ACCOUNT CHANGE COLUMN INTEREST SAVING_INTEREST DOUBLE NOT NULL DEFAULT 0;

-- DROP COLUMN NAME
ALTER TABLE ACCOUNT DROP COLUMN SAVING_INTEREST;

-- RENAME THE TABLE
ALTER TABLE ACCOUNT RENAME TO ACCOUNT_DETAILS;





