SELECT * FROM temp.Customer;

-- DATE MODIFICATION LANGUAGE (DML)
-- INSERT
-- UPDATE
-- DELETE
-- REPLACE

CREATE TABLE CUSTOMER (
ID INT PRIMARY KEY,
CUSTOMER_NAME VARCHAR(25),
ADDRESS VARCHAR(225),
GENDER CHAR(2),
CITY VARCHAR(225),
PINCODE INT
); 

DROP TABLE CUSTOMER;

SELECT * FROM CUSTOMER;

-- INSERT 

INSERT INTO CUSTOMER (ID, CUSTOMER_NAME, ADDRESS,GENDER, CITY, PINCODE)
VALUES (1356,'KAVYA', 'KHARAR', 'M', 'CHANDIGARH', 140301);

INSERT INTO CUSTOMER VALUES (1, 'ARSHIT', 'KHARAR', 'M', 'CHANDIGARH', 14301);

INSERT INTO CUSTOMER (ID, CUSTOMER_NAME) 
VALUES (121, 'BABLU');

-- UPDATE
UPDATE CUSTOMER SET ADDRESS = 'MUMBAI', GENDER = 'M' WHERE ID = 121;

-- UPDATE MULTIPLE ROWS
SET SQL_SAFE_UPDATES = 0;
UPDATE CUSTOMER SET PINCODE = 110000;
UPDATE CUSTOMER SET PINCODE = PINCODE + 1;

-- DELETE
DELETE FROM CUSTOMER WHERE ID = 121;

-- DELETE TABLE
DELETE FROM CUSTOMER;

-- ON DELETE CASCADE
-- ON DELETE SET NULL


